# Makefile.in generated by automake 1.10.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






pkgdatadir = $(datadir)/tempo2
pkglibdir = $(libdir)/tempo2
pkgincludedir = $(includedir)/tempo2
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i386-apple-darwin10.8.0
host_triplet = i386-apple-darwin10.8.0
bin_PROGRAMS = tempo2$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) \
	$(libtempo2_la_include_HEADERS) \
	$(libtempo2pred_la_include_HEADERS) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure COPYING config/compile \
	config/config.guess config/config.sub config/depcomp \
	config/install-sh config/ltmain.sh config/missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/autoconf/cfitsio.m4 \
	$(top_srcdir)/autoconf/etr_socket_nsl.m4 \
	$(top_srcdir)/autoconf/fftw.m4 $(top_srcdir)/autoconf/local.m4 \
	$(top_srcdir)/autoconf/ltdl.m4 \
	$(top_srcdir)/autoconf/mjk_fortran_test.m4 \
	$(top_srcdir)/autoconf/package.m4 \
	$(top_srcdir)/autoconf/pgplot.m4 $(top_srcdir)/autoconf/x11.m4 \
	$(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" \
	"$(DESTDIR)$(libtempo2_la_includedir)" \
	"$(DESTDIR)$(libtempo2pred_la_includedir)"
libLTLIBRARIES_INSTALL = $(INSTALL)
LTLIBRARIES = $(lib_LTLIBRARIES)
libtempo2_la_DEPENDENCIES = sofa/libsofa.la
am__objects_1 =
am_libtempo2_la_OBJECTS = $(am__objects_1) preProcess.lo \
	calculate_bclt.lo T2toolkit.lo TKfit.lo doFit.lo \
	readTimfile.lo formBats.lo initialise.lo shapiro_delay.lo \
	textOutput.lo displayParameters.lo formResiduals.lo \
	libtempo2_la-jpleph.lo toa2utc.lo tai2tt.lo dm_delays.lo \
	getInputs.lo readEphemeris.lo tt2tdb.lo utc2tai.lo tai2ut1.lo \
	get_obsCoord.lo readParfile.lo units.lo vectorPulsar.lo \
	tempo2Util.lo polyco.lo dynarr.lo clkcorr.lo observatory.lo \
	storePrecision.lo readJBO_bat.lo MSSmodel.lo BTmodel.lo \
	BTJmodel.lo BTXmodel.lo ELL1model.lo DDGRmodel.lo DDmodel.lo \
	DDKmodel.lo DDSmodel.lo DDHmodel.lo ELL1Hmodel.lo T2model.lo \
	ifteph.lo eop.lo tropo.lo bootstrap.lo cheby2d_int.lo \
	libtempo2_la-cheby2d.lo tabulatedfunction.lo \
	libtempo2_la-t1polyco.lo libtempo2_la-tempo2pred.lo \
	secularMotion.lo sw_delay.lo global.lo preProcessSimple.lo \
	constraints.lo
libtempo2_la_OBJECTS = $(am_libtempo2_la_OBJECTS)
libtempo2pred_la_LIBADD =
am_libtempo2pred_la_OBJECTS = $(am__objects_1) \
	libtempo2pred_la-tempo2pred.lo libtempo2pred_la-cheby2d.lo \
	libtempo2pred_la-t1polyco.lo
libtempo2pred_la_OBJECTS = $(am_libtempo2pred_la_OBJECTS)
libtempo2pred_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(libtempo2pred_la_CFLAGS) \
	$(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS)
am_tempo2_OBJECTS = $(am__objects_1) tempo2.$(OBJEXT)
tempo2_OBJECTS = $(am_tempo2_OBJECTS)
am__DEPENDENCIES_1 =
tempo2_DEPENDENCIES = libtempo2.la sofa/libsofa.la \
	$(am__DEPENDENCIES_1)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__depfiles_maybe = depfiles
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libtempo2_la_SOURCES) $(libtempo2pred_la_SOURCES) \
	$(tempo2_SOURCES)
DIST_SOURCES = $(libtempo2_la_SOURCES) $(libtempo2pred_la_SOURCES) \
	$(tempo2_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
libtempo2_la_includeHEADERS_INSTALL = $(INSTALL_HEADER)
libtempo2pred_la_includeHEADERS_INSTALL = $(INSTALL_HEADER)
HEADERS = $(libtempo2_la_include_HEADERS) \
	$(libtempo2pred_la_include_HEADERS)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/jonathangair/code/C_C++/Tempo2/tempo2-2012.6.1/config/missing --run aclocal-1.10
AMTAR = ${SHELL} /Users/jonathangair/code/C_C++/Tempo2/tempo2-2012.6.1/config/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /Users/jonathangair/code/C_C++/Tempo2/tempo2-2012.6.1/config/missing --run autoconf
AUTOHEADER = ${SHELL} /Users/jonathangair/code/C_C++/Tempo2/tempo2-2012.6.1/config/missing --run autoheader
AUTOMAKE = ${SHELL} /Users/jonathangair/code/C_C++/Tempo2/tempo2-2012.6.1/config/missing --run automake-1.10
AWK = awk
CC = gcc
CCDEPMODE = depmode=gcc3
CFITSIO_CFLAGS = 
CFITSIO_LIBS = -lcfitsio -lm 
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = -I//include -I/opt/local/include -I/usr/local/include 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DSYMUTIL = dsymutil
ECHO = /bin/echo
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
F77 = gfortran
FFLAGS = -g -O2
FFTW_CFLAGS =  
FFTW_LIBS = -lfftw3 -lm 
FLIBS =  -L/opt/local/lib/gcc44/gcc/x86_64-apple-darwin10/4.4.5 -L/opt/local/lib/gcc44/gcc/x86_64-apple-darwin10/4.4.5/../../.. -lgfortranbegin -lgfortran
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = -L//lib -L/opt/local/lib -L/usr/local/lib 
LIBADD_DL =  
LIBADD_DLD_LINK = 
LIBADD_DLOPEN = 
LIBADD_SHL_LOAD = 
LIBOBJS = 
LIBS = -lm 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTLIBOBJS = 
LT_DLLOADERS =  dlopen.la
LT_DLPREOPEN = -dlpreopen dlopen.la 
MAKEINFO = ${SHELL} /Users/jonathangair/code/C_C++/Tempo2/tempo2-2012.6.1/config/missing --run makeinfo
MKDIR_P = config/install-sh -c -d
NMEDIT = nmedit
OBJEXT = o
PACKAGE = tempo2
PACKAGE_BUGREPORT = george.hobbs@csiro.au
PACKAGE_NAME = Tempo2
PACKAGE_STRING = Tempo2 2012.6.1
PACKAGE_TARNAME = tempo2
PACKAGE_URL = 
PACKAGE_VERSION = 2012.6.1
PATH_SEPARATOR = :
PGPLOT_CFLAGS = 
PGPLOT_LIBS =  -lcpgplot -lpgplot  -L/opt/local/lib/gcc44/gcc/x86_64-apple-darwin10/4.4.5 -L/opt/local/lib/gcc44/gcc/x86_64-apple-darwin10/4.4.5/../../.. -lgfortranbegin -lgfortran 
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
SOCKET_LIBS = 
STRIP = strip
T2ARCH = darwin10.0
TEMPO2 = /Users/jonathangair/code/C_C++/Tempo2/tempo2runtime
TEMPO2_DIR = /Users/jonathangair/code/C_C++/Tempo2/tempo2runtime
TEMPO2_PLUG_INSTALL = /Users/jonathangair/code/C_C++/Tempo2/tempo2runtime/plugins/
VERSION = 2012.6.1
XMKMF = 
X_CFLAGS = 
X_EXTRA_LIBS = 
X_LIBS = 
X_PRE_LIBS =  -lSM -lICE
abs_builddir = /Users/jonathangair/code/C_C++/Tempo2/tempo2-2012.6.1
abs_srcdir = /Users/jonathangair/code/C_C++/Tempo2/tempo2-2012.6.1
abs_top_builddir = /Users/jonathangair/code/C_C++/Tempo2/tempo2-2012.6.1
abs_top_srcdir = /Users/jonathangair/code/C_C++/Tempo2/tempo2-2012.6.1
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_F77 = gfortran
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i386-apple-darwin10.8.0
build_alias = 
build_cpu = i386
build_os = darwin10.8.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i386-apple-darwin10.8.0
host_alias = 
host_cpu = i386
host_os = darwin10.8.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /Users/jonathangair/code/C_C++/Tempo2/tempo2-2012.6.1/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(top_builddir)/config/install-sh -c -d
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /Users/jonathangair/code/C_C++/Tempo2/tempo2runtime
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I autoconf
SUBDIRS = sofa . #plugin
DIST_SUBDIRS = sofa plugin unsupported_plugins
lib_LTLIBRARIES = libtempo2.la libtempo2pred.la

# Source files used by plugins that are not part of libtempo2
xtra_dist_sources = choleskyRoutines.C choleskyRoutines.h

#It'd be better to sort out which headers are neaded by which target, but I'm to busy to do that right now.
headers = GWgeneralsim_anisotropic.h GWgeneralsim.h GWsim_anisotropic.h GWsim_dipole.h GWsim.h T2toolkit.h TKfit.h TKspectrum.h dynarr.h ifteph.h jpl_int.h jpleph.h read_fortran.h read_fortran2.h tabulatedfunction.h tempo2.h tempo2Util.h tempo2pred.h tempo2pred_int.h constraints.h
libtempo2_la_SOURCES = $(headers) preProcess.C calculate_bclt.C T2toolkit.C TKfit.C doFit.C readTimfile.C formBats.C initialise.C shapiro_delay.C textOutput.C displayParameters.C formResiduals.C jpleph.c toa2utc.C tai2tt.C dm_delays.C getInputs.C readEphemeris.C tt2tdb.C utc2tai.C tai2ut1.C  get_obsCoord.C readParfile.C units.C vectorPulsar.C tempo2Util.C polyco.C dynarr.C clkcorr.C observatory.C storePrecision.C readJBO_bat.C MSSmodel.C BTmodel.C BTJmodel.C BTXmodel.C ELL1model.C DDGRmodel.C DDmodel.C DDKmodel.C DDSmodel.C DDHmodel.C ELL1Hmodel.C T2model.C ifteph.C eop.C tropo.C bootstrap.C cheby2d_int.C cheby2d.c tabulatedfunction.C t1polyco.c tempo2pred.c secularMotion.C sw_delay.C global.C preProcessSimple.C constraints.C
libtempo2_la_LIBADD = sofa/libsofa.la
libtempo2_la_CFLAGS = -fPIC
#libtempo2_la_LDFLAGS = -static
libtempo2_la_includedir = $(includedir)
libtempo2_la_include_HEADERS = tempo2.h
libtempo2pred_la_SOURCES = $(headers) tempo2pred.c cheby2d.c t1polyco.c
libtempo2pred_la_CFLAGS = -fPIC
#libtempo2pred_la_LDFLAGS = -static
libtempo2pred_la_includedir = $(includedir)
libtempo2pred_la_include_HEADERS = tempo2pred.h tempo2pred_int.h
tempo2_SOURCES = $(headers) tempo2.C 
tempo2_LDADD = libtempo2.la sofa/libsofa.la  -L/opt/local/lib/gcc44/gcc/x86_64-apple-darwin10/4.4.5 -L/opt/local/lib/gcc44/gcc/x86_64-apple-darwin10/4.4.5/../../.. -lgfortranbegin -lgfortran $(LIBADD_DLOPEN)

# Specify to include the T2runtime in distributions
EXTRA_DIST = T2runtime $(xtra_dist_sources)
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .C .c .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign '; \
	      cd $(srcdir) && $(AUTOMAKE) --foreign  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f=$(am__strip_dir) \
	    echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(libLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) '$$p' '$(DESTDIR)$(libdir)/$$f'"; \
	    $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(libLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) "$$p" "$(DESTDIR)$(libdir)/$$f"; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  p=$(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$p'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$p"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libtempo2.la: $(libtempo2_la_OBJECTS) $(libtempo2_la_DEPENDENCIES) 
	$(CXXLINK) -rpath $(libdir) $(libtempo2_la_OBJECTS) $(libtempo2_la_LIBADD) $(LIBS)
libtempo2pred.la: $(libtempo2pred_la_OBJECTS) $(libtempo2pred_la_DEPENDENCIES) 
	$(libtempo2pred_la_LINK) -rpath $(libdir) $(libtempo2pred_la_OBJECTS) $(libtempo2pred_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	     || test -f $$p1 \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  echo " rm -f $$p $$f"; \
	  rm -f $$p $$f ; \
	done
tempo2$(EXEEXT): $(tempo2_OBJECTS) $(tempo2_DEPENDENCIES) 
	@rm -f tempo2$(EXEEXT)
	$(CXXLINK) $(tempo2_OBJECTS) $(tempo2_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/BTJmodel.Plo
include ./$(DEPDIR)/BTXmodel.Plo
include ./$(DEPDIR)/BTmodel.Plo
include ./$(DEPDIR)/DDGRmodel.Plo
include ./$(DEPDIR)/DDHmodel.Plo
include ./$(DEPDIR)/DDKmodel.Plo
include ./$(DEPDIR)/DDSmodel.Plo
include ./$(DEPDIR)/DDmodel.Plo
include ./$(DEPDIR)/ELL1Hmodel.Plo
include ./$(DEPDIR)/ELL1model.Plo
include ./$(DEPDIR)/MSSmodel.Plo
include ./$(DEPDIR)/T2model.Plo
include ./$(DEPDIR)/T2toolkit.Plo
include ./$(DEPDIR)/TKfit.Plo
include ./$(DEPDIR)/bootstrap.Plo
include ./$(DEPDIR)/calculate_bclt.Plo
include ./$(DEPDIR)/cheby2d_int.Plo
include ./$(DEPDIR)/clkcorr.Plo
include ./$(DEPDIR)/constraints.Plo
include ./$(DEPDIR)/displayParameters.Plo
include ./$(DEPDIR)/dm_delays.Plo
include ./$(DEPDIR)/doFit.Plo
include ./$(DEPDIR)/dynarr.Plo
include ./$(DEPDIR)/eop.Plo
include ./$(DEPDIR)/formBats.Plo
include ./$(DEPDIR)/formResiduals.Plo
include ./$(DEPDIR)/getInputs.Plo
include ./$(DEPDIR)/get_obsCoord.Plo
include ./$(DEPDIR)/global.Plo
include ./$(DEPDIR)/ifteph.Plo
include ./$(DEPDIR)/initialise.Plo
include ./$(DEPDIR)/libtempo2_la-cheby2d.Plo
include ./$(DEPDIR)/libtempo2_la-jpleph.Plo
include ./$(DEPDIR)/libtempo2_la-t1polyco.Plo
include ./$(DEPDIR)/libtempo2_la-tempo2pred.Plo
include ./$(DEPDIR)/libtempo2pred_la-cheby2d.Plo
include ./$(DEPDIR)/libtempo2pred_la-t1polyco.Plo
include ./$(DEPDIR)/libtempo2pred_la-tempo2pred.Plo
include ./$(DEPDIR)/observatory.Plo
include ./$(DEPDIR)/polyco.Plo
include ./$(DEPDIR)/preProcess.Plo
include ./$(DEPDIR)/preProcessSimple.Plo
include ./$(DEPDIR)/readEphemeris.Plo
include ./$(DEPDIR)/readJBO_bat.Plo
include ./$(DEPDIR)/readParfile.Plo
include ./$(DEPDIR)/readTimfile.Plo
include ./$(DEPDIR)/secularMotion.Plo
include ./$(DEPDIR)/shapiro_delay.Plo
include ./$(DEPDIR)/storePrecision.Plo
include ./$(DEPDIR)/sw_delay.Plo
include ./$(DEPDIR)/tabulatedfunction.Plo
include ./$(DEPDIR)/tai2tt.Plo
include ./$(DEPDIR)/tai2ut1.Plo
include ./$(DEPDIR)/tempo2.Po
include ./$(DEPDIR)/tempo2Util.Plo
include ./$(DEPDIR)/textOutput.Plo
include ./$(DEPDIR)/toa2utc.Plo
include ./$(DEPDIR)/tropo.Plo
include ./$(DEPDIR)/tt2tdb.Plo
include ./$(DEPDIR)/units.Plo
include ./$(DEPDIR)/utc2tai.Plo
include ./$(DEPDIR)/vectorPulsar.Plo

.C.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	mv -f $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.C.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	mv -f $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.C.lo:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	mv -f $$depbase.Tpo $$depbase.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

.c.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	mv -f $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ $<

.c.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	mv -f $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	mv -f $$depbase.Tpo $$depbase.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

libtempo2_la-jpleph.lo: jpleph.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2_la_CFLAGS) $(CFLAGS) -MT libtempo2_la-jpleph.lo -MD -MP -MF $(DEPDIR)/libtempo2_la-jpleph.Tpo -c -o libtempo2_la-jpleph.lo `test -f 'jpleph.c' || echo '$(srcdir)/'`jpleph.c
	mv -f $(DEPDIR)/libtempo2_la-jpleph.Tpo $(DEPDIR)/libtempo2_la-jpleph.Plo
#	source='jpleph.c' object='libtempo2_la-jpleph.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2_la_CFLAGS) $(CFLAGS) -c -o libtempo2_la-jpleph.lo `test -f 'jpleph.c' || echo '$(srcdir)/'`jpleph.c

libtempo2_la-cheby2d.lo: cheby2d.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2_la_CFLAGS) $(CFLAGS) -MT libtempo2_la-cheby2d.lo -MD -MP -MF $(DEPDIR)/libtempo2_la-cheby2d.Tpo -c -o libtempo2_la-cheby2d.lo `test -f 'cheby2d.c' || echo '$(srcdir)/'`cheby2d.c
	mv -f $(DEPDIR)/libtempo2_la-cheby2d.Tpo $(DEPDIR)/libtempo2_la-cheby2d.Plo
#	source='cheby2d.c' object='libtempo2_la-cheby2d.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2_la_CFLAGS) $(CFLAGS) -c -o libtempo2_la-cheby2d.lo `test -f 'cheby2d.c' || echo '$(srcdir)/'`cheby2d.c

libtempo2_la-t1polyco.lo: t1polyco.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2_la_CFLAGS) $(CFLAGS) -MT libtempo2_la-t1polyco.lo -MD -MP -MF $(DEPDIR)/libtempo2_la-t1polyco.Tpo -c -o libtempo2_la-t1polyco.lo `test -f 't1polyco.c' || echo '$(srcdir)/'`t1polyco.c
	mv -f $(DEPDIR)/libtempo2_la-t1polyco.Tpo $(DEPDIR)/libtempo2_la-t1polyco.Plo
#	source='t1polyco.c' object='libtempo2_la-t1polyco.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2_la_CFLAGS) $(CFLAGS) -c -o libtempo2_la-t1polyco.lo `test -f 't1polyco.c' || echo '$(srcdir)/'`t1polyco.c

libtempo2_la-tempo2pred.lo: tempo2pred.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2_la_CFLAGS) $(CFLAGS) -MT libtempo2_la-tempo2pred.lo -MD -MP -MF $(DEPDIR)/libtempo2_la-tempo2pred.Tpo -c -o libtempo2_la-tempo2pred.lo `test -f 'tempo2pred.c' || echo '$(srcdir)/'`tempo2pred.c
	mv -f $(DEPDIR)/libtempo2_la-tempo2pred.Tpo $(DEPDIR)/libtempo2_la-tempo2pred.Plo
#	source='tempo2pred.c' object='libtempo2_la-tempo2pred.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2_la_CFLAGS) $(CFLAGS) -c -o libtempo2_la-tempo2pred.lo `test -f 'tempo2pred.c' || echo '$(srcdir)/'`tempo2pred.c

libtempo2pred_la-tempo2pred.lo: tempo2pred.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2pred_la_CFLAGS) $(CFLAGS) -MT libtempo2pred_la-tempo2pred.lo -MD -MP -MF $(DEPDIR)/libtempo2pred_la-tempo2pred.Tpo -c -o libtempo2pred_la-tempo2pred.lo `test -f 'tempo2pred.c' || echo '$(srcdir)/'`tempo2pred.c
	mv -f $(DEPDIR)/libtempo2pred_la-tempo2pred.Tpo $(DEPDIR)/libtempo2pred_la-tempo2pred.Plo
#	source='tempo2pred.c' object='libtempo2pred_la-tempo2pred.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2pred_la_CFLAGS) $(CFLAGS) -c -o libtempo2pred_la-tempo2pred.lo `test -f 'tempo2pred.c' || echo '$(srcdir)/'`tempo2pred.c

libtempo2pred_la-cheby2d.lo: cheby2d.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2pred_la_CFLAGS) $(CFLAGS) -MT libtempo2pred_la-cheby2d.lo -MD -MP -MF $(DEPDIR)/libtempo2pred_la-cheby2d.Tpo -c -o libtempo2pred_la-cheby2d.lo `test -f 'cheby2d.c' || echo '$(srcdir)/'`cheby2d.c
	mv -f $(DEPDIR)/libtempo2pred_la-cheby2d.Tpo $(DEPDIR)/libtempo2pred_la-cheby2d.Plo
#	source='cheby2d.c' object='libtempo2pred_la-cheby2d.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2pred_la_CFLAGS) $(CFLAGS) -c -o libtempo2pred_la-cheby2d.lo `test -f 'cheby2d.c' || echo '$(srcdir)/'`cheby2d.c

libtempo2pred_la-t1polyco.lo: t1polyco.c
	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2pred_la_CFLAGS) $(CFLAGS) -MT libtempo2pred_la-t1polyco.lo -MD -MP -MF $(DEPDIR)/libtempo2pred_la-t1polyco.Tpo -c -o libtempo2pred_la-t1polyco.lo `test -f 't1polyco.c' || echo '$(srcdir)/'`t1polyco.c
	mv -f $(DEPDIR)/libtempo2pred_la-t1polyco.Tpo $(DEPDIR)/libtempo2pred_la-t1polyco.Plo
#	source='t1polyco.c' object='libtempo2pred_la-t1polyco.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libtempo2pred_la_CFLAGS) $(CFLAGS) -c -o libtempo2pred_la-t1polyco.lo `test -f 't1polyco.c' || echo '$(srcdir)/'`t1polyco.c

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
install-libtempo2_la_includeHEADERS: $(libtempo2_la_include_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(libtempo2_la_includedir)" || $(MKDIR_P) "$(DESTDIR)$(libtempo2_la_includedir)"
	@list='$(libtempo2_la_include_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(libtempo2_la_includeHEADERS_INSTALL) '$$d$$p' '$(DESTDIR)$(libtempo2_la_includedir)/$$f'"; \
	  $(libtempo2_la_includeHEADERS_INSTALL) "$$d$$p" "$(DESTDIR)$(libtempo2_la_includedir)/$$f"; \
	done

uninstall-libtempo2_la_includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(libtempo2_la_include_HEADERS)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(libtempo2_la_includedir)/$$f'"; \
	  rm -f "$(DESTDIR)$(libtempo2_la_includedir)/$$f"; \
	done
install-libtempo2pred_la_includeHEADERS: $(libtempo2pred_la_include_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(libtempo2pred_la_includedir)" || $(MKDIR_P) "$(DESTDIR)$(libtempo2pred_la_includedir)"
	@list='$(libtempo2pred_la_include_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(libtempo2pred_la_includeHEADERS_INSTALL) '$$d$$p' '$(DESTDIR)$(libtempo2pred_la_includedir)/$$f'"; \
	  $(libtempo2pred_la_includeHEADERS_INSTALL) "$$d$$p" "$(DESTDIR)$(libtempo2pred_la_includedir)/$$f"; \
	done

uninstall-libtempo2pred_la_includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(libtempo2pred_la_include_HEADERS)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(libtempo2pred_la_includedir)/$$f'"; \
	  rm -f "$(DESTDIR)$(libtempo2pred_la_includedir)/$$f"; \
	done

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonemtpy = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      tags="$$tags $$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d $(distdir) || mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	    distdir=`$(am__cd) $(distdir) && pwd`; \
	    top_distdir=`$(am__cd) $(top_distdir) && pwd`; \
	    (cd $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$top_distdir" \
	        distdir="$$distdir/$$subdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) \
	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
	  dist-hook
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  unlzma -c $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(HEADERS) config.h
install-binPROGRAMS: install-libLTLIBRARIES

installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(libtempo2_la_includedir)" "$(DESTDIR)$(libtempo2pred_la_includedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

info: info-recursive

info-am:

install-data-am: install-libtempo2_la_includeHEADERS \
	install-libtempo2pred_la_includeHEADERS
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-data-hook

install-dvi: install-dvi-recursive

install-exec-am: install-binPROGRAMS install-libLTLIBRARIES

install-html: install-html-recursive

install-info: install-info-recursive

install-man:

install-pdf: install-pdf-recursive

install-ps: install-ps-recursive

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-libLTLIBRARIES \
	uninstall-libtempo2_la_includeHEADERS \
	uninstall-libtempo2pred_la_includeHEADERS

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) install-am \
	install-data-am install-strip

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am am--refresh check check-am clean clean-binPROGRAMS \
	clean-generic clean-libLTLIBRARIES clean-libtool ctags \
	ctags-recursive dist dist-all dist-bzip2 dist-gzip dist-hook \
	dist-lzma dist-shar dist-tarZ dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-data-hook install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-libLTLIBRARIES \
	install-libtempo2_la_includeHEADERS \
	install-libtempo2pred_la_includeHEADERS install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-recursive \
	uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-libLTLIBRARIES uninstall-libtempo2_la_includeHEADERS \
	uninstall-libtempo2pred_la_includeHEADERS


# This clears out any CVS files that might get in our distribution
dist-hook:
	rm -rf `find $(distdir)/T2runtime -name CVS`
	rm -rf $(distdir)/T2runtime/plugins/*
	rm -rf $(distdir)/unsupported_plugins/built_plugins/*
	rm -rf `find $(distdir)/unsupported_plugins/ -name CVS`
	rm -rf `find $(distdir)/unsupported_plugins/ -name '*.o'`

plugins-install: all
	$(MAKE) -C plugin plugins-install

plugins: all
	$(MAKE) -C plugin

unsupported:
	$(MAKE) -C unsupported_plugins

unsupported-install: unsupported
	$(MAKE) -C unsupported_plugins install

.PHONY: plugins-install plugins unsupported_plugins

install-data-hook:
	@echo ""
	@echo ""
	@echo "*** NOTICE ***"
	@echo "Plugins are no longer installed by default"
	@echo "Use: 'make plugins-install' to install them"
	@echo ""
	@echo ""
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
